apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: mynodeapp-metrics
  namespace: default
  labels:
    app: mynodeapp
    release: monitoring
spec:
  selector:
    matchLabels:
      app: mynodeapp
  endpoints:
    - port: http
      path: /metrics
      interval: 15s
      scrapeTimeout: 10s